#!/usr/bin/env bash
#
# nosj - json parser in pure bash

tokenize() {
    while read -rn 1 char; do
        case $char in
            \{|\}|\[|\]|,)
                case $string in
                    1) tokens+=$char ;;
                    *) tokens+=$'\n'$char$'\n' ;;
                esac
            ;;

            :)
                case $string in
                    1) tokens+=: ;;
                    *) tokens+=%%:::%% ;;
                esac
            ;;

            \"|\')
                ((string=string == 1 ? 0 : 1))
            ;;

            [[:space:]])
                [[ $string == 1 ]] &&
                    tokens+=$char
            ;;

            *) tokens+=$char ;;
        esac
    done < "$1"

    mapfile -t tokens <<< "$tokens"
}

parse() {
    for ((i=0;i<${#tokens[@]};i++)) {
        case ${tokens[i]} in
            \{|\[)
                objects+=("${tokens[i-1]}")
            ;;

            \}|\])
                unset 'objects[-1]'
            ;;

            *"%%:::%%"*)
                key=${objects[*]//'%%:::%%'/_}${tokens[i]/'%%:::%%'*}
                val=${tokens[i]/*'%%:::%%'}

                [[ $val ]] &&
                    json+=("${key//[^[a-zA-Z0-9]/_}+=('$val')")
            ;;

            "") ;;
        esac

        unset key val
    }

    declare -axg "${json[@]}"
    printf '%s\n' "${json[@]}"
}

main() {
    IFS=
    tokenize "${1:-/dev/stdin}"
    parse
}

main "$@"
